backend:
    name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"
#publish_mode: editorial_workflow
display_url: http://localhost:3000
baseURL: http://localhost:3000

collections: # A list of collections the CMS should be able to edit
    -   name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
        label: "Post" # Used in the UI, ie.: "New Post"
        folder: "site/content/post" # The path to the folder where the documents are stored
        create: true # Allow users to create new documents in this collection
        fields: # The fields each document in this collection have
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Publish Date", name: "date", widget: "datetime"}
            - {label: "Intro Blurb", name: "description", widget: "text"}
            - {label: "Image", name: "image", widget: "image", required: false}
            - {label: "Body", name: "body", widget: "markdown"}
    
    -   name: "projects"
        label: "Project"
        folder: "site/content/project"
        create: true
        fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Show Slider", name: "showSlider", widget: "boolean", required: false}
            -   label: "Slider"
                name: "sliderImages"
                widget: "list"
                required: false
                field: {label: Image, name: image, widget: image}
            - {label: "Introduction Section", name: "intro_section", required: false, widget: "object", fields: [
                {label: "Use Two Columns", name: "useTwoColumns", widget: boolean, required: false},
                {label: "Text Column 1", name: "textCol1", widget: markdown},
                {label: "Text Column 2", name: "textCol2", widget: markdown},
                ]}
            - {label: "Show Video", name: "showVideo", widget: boolean, required: false}
            - {label: "Representative Video/Photo", name: "videoPhoto", required: false, widget: "object", fields: [
            {label: "Title", name: "title", widget: markdown},
            {label: "Representative Video to run in background: format should be .mp4", name: "video", widget: file}
            ]}
            - {label: "Counter Section", name: "counter", widget: object, required: false, fields: [
                {label: "Show Counter", name: "showCounter", widget: boolean, required: false},
                {label: "Counter Background Color", name: "counter_background_color", widget: color, required: false},
                {label: "Counter", name: "counter_elements", widget: "list", required: false, fields: [
                {label: "Counter text", name: "counterText", widget: string},
                {label: "Counter number", name: "counterValue", widget: string},
                {label: "Counter Color", name: "counterColor", widget: color},
                ]}
            ]}
           

            - {label: "Show Text Photo Section", name: "showTextPhotoSection", widget: boolean, required: false}
            - {label: "Text Photo Section", name: "textPhotoSection", widget: "list", required: false, fields: [
            {label: "Section Image", name: "sectionImage", widget: image},
            {label: "Section Details", name: "sectionText", widget: markdown},
            {label: "Reverse order", name: "reverseOrder", widget: boolean, required: false},
            ]}
            -   label: "Gallery"
                name: "gallery"
                widget: "object"
                required: false
                fields: [
                     {label: "Title", name: "title", widget: markdown},
                     {label: "Photos", name: "photos", widget: list, fields: [
                        {label: "Image", name: "image", widget: image}
                ]}]

    -   name: "pages"
        label: "Pages"
        files:
            -   file: "site/content/_index.md"
                label: "Home Page"
                name: "home"
                fields:
                    - {label: Title, name: title, widget: string}
                    - {label: Subtitle, name: subtitle, widget: string}
                    - {label: Image, name: image, widget: image}
                    - {label: "Project Cards", name: "project_cards", widget: object, required:false, fields: [
                        {label: "Projects", name: "projects", widget: list, fields: [
                            {label: "Project Title", name: "project_title", widget: text},
                            {label: "Project Description", name: "project_description", widget: text},
                            {label: "Project Icon", name: "project_icon", widget: file},
                            {label: "Background Color", name: "background_color", widget: color},
                            {label: "Button Text", name: "button_text", widget: string},
                            {label: "Button URL", name: "button_url", widget: string},
                    ]}
                    
                    ]}
                    - {label: "Text Photo Section", name: "textPhotoSection", widget: "list", required: false, fields: [
                    {label: "Section Image", name: "sectionImage", widget: image},
                    {label: "Section Details", name: "sectionText", widget: markdown},
                    {label: "Reverse order", name: "reverseOrder", widget: boolean, required: false},
                    ]}
                    
            -   file: "site/content/contact/_index.md"
                label: "Contact Page"
                name: "contact"
                fields:
                    - {label: Title, name: title, widget: string}
                    - {label: Logo, name: logo, widget: image}
                    - {label: Body, name: body, widget: markdown}
                    -   label: Contact Entries
                        name: contact_entries
                        widget: list
                        fields:
                            -   label: Heading
                                name: heading
                                widget: string
                            -   label: Text
                                name: text
                                widget: text
            -   file: "site/content/products/_index.md"
                label: "Products Page"
                name: "products"
                fields:
                    - {label: Title, name: title, widget: string}
                    - {label: Image, name: image, widget: image}
                    - {label: Heading, name: heading, widget: string}
                    - {label: Description, name: description, widget: string}
                    - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
                    - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
                    - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
                    - {label: Full_image, name: full_image, widget: image}
                    - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
            -   file: "site/content/values/_index.md"
                label: "Values Page"
                name: "values"
                fields:
                    - {label: Title, name: title, widget: string}
                    - {label: Image, name: image, widget: image}
                    -   label: Values
                        name: values
                        widget: list
                        fields:
                            - {label: Heading, name: heading, widget: string}
                            - {label: Text, name: text, widget: text}
                            - {label: Image, name: imageUrl, widget: image}
